hub:
  world: "world"
  x: 0
  y: 64
  z: 0

farm:
  world: "world"
  x: 100
  y: 64
  z: 100

coalmine:
  world: "world"
  x: 200
  y: 64
  z: 200

woodland:
  world: "world"
  x: 300
  y: 64
  z: 300

graveyard:
  world: "world"
  x: 400
  y: 64
  z: 400

desert:
  world: "world"
  x: 500
  y: 64
  z: 500

spiderden:
  world: "world"
  x: 600
  y: 64
  z: 600

nether:
  world: "nether"
  x: 100
  y: 64
  z: 100

end:
  world: "end"
  x: 0
  y: 64
  z: 0

pvp:
  world: "world"
  x: 700
  y: 64
  z: 700
  
